# Generated by Django 4.2.3 on 2023-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('capibara_format', models.CharField(max_length=255)),
                ('capibara_slang', models.CharField(max_length=255)),
                ('capibara_phrases', models.JSONField()),
            ],
        ),
    ]
